name: flutter_displaymode
description: A Flutter plugin to set display mode on Android.
version: 0.3.0-nullsafety.0
homepage: https://github.com/ajinasokan/flutter_displaymode

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">1.22.6"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ajinasokan.flutterdisplaymode
        pluginClass: DisplayModePlugin
